// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartApartmentAplication.MyContext;

namespace SmartApartmentAplication.Migrations
{
    [DbContext(typeof(SmartApartmentContext))]
    [Migration("20210713135304_AddingMgmtIDField")]
    partial class AddingMgmtIDField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartApartmentAplication.Features.Mgmt.mgmtDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("isActive")
                        .HasColumnType("int");

                    b.Property<string>("market")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mgmtID")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("mgmtDetail");
                });

            modelBuilder.Entity("SmartApartmentAplication.Features.Mgmt.mgmtHeader", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("isActive")
                        .HasColumnType("int");

                    b.Property<int?>("mgmtid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("mgmtid");

                    b.ToTable("mgmtHeader");
                });

            modelBuilder.Entity("SmartApartmentAplication.Features.Mgmt.mgmtHeader", b =>
                {
                    b.HasOne("SmartApartmentAplication.Features.Mgmt.mgmtDetail", "mgmt")
                        .WithMany()
                        .HasForeignKey("mgmtid");

                    b.Navigation("mgmt");
                });
#pragma warning restore 612, 618
        }
    }
}
